"""Copy pure upstream functions verbatim; never edit generated rules by hand."""
import argparse
import ast
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT = ROOT.parents[1] / 'primeqk_online'
NAMES = ['invalid_joker_assignments', 'joker_assignment_error_message', 'is_prime',
         'is_twin_quadruplet_prime', 'find_prime_factor', 'is_semiprime',
         'is_valid_prime_by_rule', 'rule_display_name', 'CompositeError',
         'CompositeSyntaxError', 'CompositeMathError', 'map_joker_values_in_cards',
         'build_int_from_cards', 'parse_and_eval_composite']
CONSTANTS = ['_SMALL_PRIMES', 'MAX_EXP', 'JOKER_ASSIGNABLE_VALUES']
UI = ['cardButton', 'suitLabel', 'rankLabel', 'isJoker', 'isRedSuit', 'compositeSyntaxError']

def generate(source):
    main_path = source / 'github/primeqk_online_server/main.py'
    raw = main_path.read_text(encoding='utf-8-sig')
    tree = ast.parse(raw)
    pieces = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name in NAMES:
            pieces[node.name] = ast.get_source_segment(raw, node)
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id in CONSTANTS:
                    pieces[target.id] = ast.get_source_segment(raw, node)
    assert all(name in pieces for name in NAMES + CONSTANTS)
    header = '# Generated by scripts/sync_rules.py. DO NOT EDIT.\n'
    header += 'from __future__ import annotations\nfrom typing import List, Dict, Tuple\nfrom random import randrange\nfrom math import gcd\nimport time\nfrom .rules import RulePreset, PrimeRule\n\n'
    core = header + '\n\n'.join(pieces[n] for n in CONSTANTS + NAMES) + '\n'
    rules_raw = (source / 'github/primeqk_online_server/rules.py').read_text(encoding='utf-8-sig')
    ui_raw = (source / 'client-common/app.js').read_text(encoding='utf-8-sig')
    ui_parts = {}
    for name in UI:
        match = re.search(r'^function ' + name + r'\([^\n]*\{\n.*?^}', ui_raw, re.M | re.S)
        assert match, name
        ui_parts[name] = match.group()
    client = '// Generated from primeqk_online/client-common/app.js; DO NOT EDIT.\n'
    client += '\n\n'.join(ui_parts.values()) + '\nexport {' + ','.join(UI) + '};\n'
    manifest = {'source': 'primeqk_online', 'main_sha256': hashlib.sha256(main_path.read_bytes()).hexdigest(),
                'rules_sha256': hashlib.sha256((source / 'github/primeqk_online_server/rules.py').read_bytes()).hexdigest(),
                'client_sha256': hashlib.sha256((source / 'client-common/app.js').read_bytes()).hexdigest(),
                'function_hash_normalization': 'UTF-8, LF, ast.get_source_segment',
                'functions': {n: hashlib.sha256(pieces[n].encode()).hexdigest() for n in NAMES + CONSTANTS},
                'ui_functions': UI}
    return {'server/vendor/core.py': core, 'server/vendor/rules.py': rules_raw,
            'server/vendor/__init__.py': '', 'src/vendor/game-ui.mjs': client,
            'server/vendor/provenance.json': json.dumps(manifest, indent=2) + '\n'}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--source', type=Path, default=DEFAULT)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in generate(args.source).items():
        path = ROOT / name
        if args.check:
            assert path.read_text(encoding='utf-8') == content, f'Upstream drift: {name}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    print('Upstream rules and card components verified.' if args.check else 'Upstream rules and card components synchronized.')
